/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeoLogsRouteImport } from './routes/geo-logs'
import { Route as DebugLogsRouteImport } from './routes/debug-logs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccessLogsRouteImport } from './routes/access-logs'
import { Route as IndexRouteImport } from './routes/index'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoLogsRoute = GeoLogsRouteImport.update({
  id: '/geo-logs',
  path: '/geo-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLogsRoute = DebugLogsRouteImport.update({
  id: '/debug-logs',
  path: '/debug-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessLogsRoute = AccessLogsRouteImport.update({
  id: '/access-logs',
  path: '/access-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-logs': typeof AccessLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/debug-logs': typeof DebugLogsRoute
  '/geo-logs': typeof GeoLogsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-logs': typeof AccessLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/debug-logs': typeof DebugLogsRoute
  '/geo-logs': typeof GeoLogsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-logs': typeof AccessLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/debug-logs': typeof DebugLogsRoute
  '/geo-logs': typeof GeoLogsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-logs'
    | '/analytics'
    | '/debug-logs'
    | '/geo-logs'
    | '/login'
    | '/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-logs'
    | '/analytics'
    | '/debug-logs'
    | '/geo-logs'
    | '/login'
    | '/map'
  id:
    | '__root__'
    | '/'
    | '/access-logs'
    | '/analytics'
    | '/debug-logs'
    | '/geo-logs'
    | '/login'
    | '/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessLogsRoute: typeof AccessLogsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DebugLogsRoute: typeof DebugLogsRoute
  GeoLogsRoute: typeof GeoLogsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-logs': {
      id: '/geo-logs'
      path: '/geo-logs'
      fullPath: '/geo-logs'
      preLoaderRoute: typeof GeoLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-logs': {
      id: '/debug-logs'
      path: '/debug-logs'
      fullPath: '/debug-logs'
      preLoaderRoute: typeof DebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-logs': {
      id: '/access-logs'
      path: '/access-logs'
      fullPath: '/access-logs'
      preLoaderRoute: typeof AccessLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessLogsRoute: AccessLogsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DebugLogsRoute: DebugLogsRoute,
  GeoLogsRoute: GeoLogsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
