"""initial schema

Revision ID: 3aabc8810af0
Revises: 
Create Date: 2026-07-05 10:48:01.129538

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '3aabc8810af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log_debug',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('access_log_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('is_malformed', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_log_debug'))
    )
    with op.batch_alter_table('access_log_debug', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_log_debug_access_log_id'), ['access_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_debug_is_malformed'), ['is_malformed'], unique=False)

    op.create_table('access_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('timestamp', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('remote_user', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('http_version', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_time', sa.Float(), nullable=False),
    sa.Column('upstream_response_time', sa.Float(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs'))
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index('ix_access_logs_host', ['host'], unique=False)
        batch_op.create_index('ix_access_logs_ip_address', ['ip_address'], unique=False)
        batch_op.create_index('ix_access_logs_method_status', ['method', 'status_code'], unique=False)
        batch_op.create_index('ix_access_logs_status_code', ['status_code'], unique=False)

    op.create_table('geo_locations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('geographic_point', Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('last_hit', sa.DateTimeUTC(timezone=True), nullable=True, comment='Timestamp of the most recent access to this location'),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_locations')),
    sa.UniqueConstraint('geohash', name='uq_geohash')
    )
    with op.batch_alter_table('geo_locations', schema=None) as batch_op:
        # idx_geo_locations_geographic_point is created automatically by geoalchemy2's
        # DDL event listener (Geography(spatial_index=True) is the default) as soon as
        # the table exists; an explicit create_index here would duplicate it.
        batch_op.create_index('ix_geo_locations_coordinates', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('ix_geo_locations_country_city', ['country_code', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_locations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_locations_last_hit'), ['last_hit'], unique=False)

    op.create_table('geo_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('timestamp', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['geo_locations.id'], name=op.f('fk_geo_events_location_id_geo_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_events'))
    )
    with op.batch_alter_table('geo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_events_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_events_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index('ix_geo_events_ip_timestamp', ['ip_address', sa.literal_column('timestamp DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_events_location_id'), ['location_id'], unique=False)
        batch_op.create_index('ix_geo_events_location_timestamp', ['location_id', sa.literal_column('timestamp DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_geo_events_timestamp_desc', ['timestamp'], unique=False, postgresql_using='brin')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_events', schema=None) as batch_op:
        batch_op.drop_index('ix_geo_events_timestamp_desc', postgresql_using='brin')
        batch_op.drop_index(batch_op.f('ix_geo_events_timestamp'))
        batch_op.drop_index('ix_geo_events_location_timestamp')
        batch_op.drop_index(batch_op.f('ix_geo_events_location_id'))
        batch_op.drop_index('ix_geo_events_ip_timestamp')
        batch_op.drop_index(batch_op.f('ix_geo_events_ip_address'))
        batch_op.drop_index(batch_op.f('ix_geo_events_hostname'))

    op.drop_table('geo_events')
    with op.batch_alter_table('geo_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_locations_last_hit'))
        batch_op.drop_index(batch_op.f('ix_geo_locations_country_code'))
        batch_op.drop_index('ix_geo_locations_country_city')
        batch_op.drop_index('ix_geo_locations_coordinates')
        # idx_geo_locations_geographic_point is dropped automatically by geoalchemy2's
        # DDL event listener when the table is dropped; see matching note in schema_upgrades().

    op.drop_table('geo_locations')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_access_logs_status_code')
        batch_op.drop_index('ix_access_logs_method_status')
        batch_op.drop_index('ix_access_logs_ip_address')
        batch_op.drop_index('ix_access_logs_host')

    op.drop_table('access_logs')
    with op.batch_alter_table('access_log_debug', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_log_debug_is_malformed'))
        batch_op.drop_index(batch_op.f('ix_access_log_debug_access_log_id'))

    op.drop_table('access_log_debug')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
