"""Generate docs/configuration.md from pydantic-settings field metadata.

The settings classes carry description= on every field — this script turns
them into the full configuration reference so docs can't drift from code.

Usage:
    uv run python scripts/generate_config_docs.py          # write the file
    uv run python scripts/generate_config_docs.py --check  # CI freshness gate
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic_settings import BaseSettings

# Running this file directly (not via `python -m`) puts scripts/ on sys.path
# instead of the repo root, so the geometrikks package import below would
# fail. Insert the repo root explicitly.
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Import via the package so nested settings classes resolve.
from geometrikks.config import settings as settings_module  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "configuration.md"

# (title, class, env prefix) — order defines document order.
SECTIONS: list[tuple[str, type[BaseSettings], str]] = [
    ("Application", settings_module.Settings, "APP_"),
    ("API server", settings_module.APISettings, "API_"),
    ("Database", settings_module.DatabaseSettings, "DB_"),
    ("GeoIP", settings_module.GeoIPSettings, "GEOIP_"),
    ("Log parser", settings_module.LogParserSettings, "LOGPARSER_"),
    ("Analytics & retention", settings_module.AnalyticsSettings, "ANALYTICS_"),
    ("Scheduler", settings_module.SchedulerSettings, "SCHEDULER_"),
    ("Vite (development only)", settings_module.ViteSettings, "VITE_"),
]

# Top-level Settings fields that are sub-models, not env vars.
SKIP_FIELDS = {"api", "database", "geoip", "logparser", "analytics", "scheduler", "vite"}
# Never document secrets' defaults verbatim.
REDACT = {"password", "license_key", "admin_password"}


def default_repr(name: str, field) -> str:
    if name in REDACT:
        return "—"
    if field.default_factory is not None:
        return "*(computed)*"
    default = field.default
    if default is None:
        return "—"
    # These render as env-var values, so use env-native forms: lowercase
    # booleans and JSON arrays/objects rather than Python repr.
    if isinstance(default, bool):
        return f"`{str(default).lower()}`"
    if isinstance(default, (list, dict)):
        return f"`{json.dumps(default)}`"
    return f"`{default}`"


def env_name(name: str, field, prefix: str) -> str:
    # A string validation_alias is absolute — it bypasses env_prefix.
    # (GeoIPSettings.account_id/license_key -> MAXMINDDB_USER_ID/MAXMINDDB_LICENSE_KEY.)
    alias = field.validation_alias
    if isinstance(alias, str):
        return alias
    return f"{prefix}{name}".upper()


def render_section(title: str, cls: type[BaseSettings], prefix: str) -> str:
    lines = [f"## {title}", "", "| Variable | Default | Description |", "|---|---|---|"]
    for name, field in cls.model_fields.items():
        if cls is settings_module.Settings and name in SKIP_FIELDS:
            continue
        env = env_name(name, field, prefix)
        desc = (field.description or "").replace("|", "\\|")
        lines.append(f"| `{env}` | {default_repr(name, field)} | {desc} |")
    lines.append("")
    return "\n".join(lines)


def build() -> str:
    parts = [
        "# Configuration Reference",
        "",
        "<!-- GENERATED by scripts/generate_config_docs.py — do not edit by hand. -->",
        "",
        "All settings are environment variables (or `.env` entries). The short",
        "list most users need is in `.env.example`; everything below is available.",
        "",
    ]
    parts.extend(render_section(*section) for section in SECTIONS)
    return "\n".join(parts) + "\n"


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT} is stale — run scripts/generate_config_docs.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
